server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: lawen
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
      template-loader-path: classpath:template
  session.store-type: none
mybatis:
  type-aliases-package: com.example.entity
  mapper-locations:
  - classpath:mapper/*.xml
  - classpath:dao/*.xml
  configuration:
    map-underscore-to-camel-case: true